[package]
name = "minetv"
version = "0.1.0"
authors = ["ZOTTCE <zottce@gmail.com>"]

[lib]
name = "watcher"
crate-type = ["dylib"]

[[bin]]
name = "minetv"

[dependencies]
winapi = "*"
kernel32-sys = "*"
user32-sys = "*"
libc = "*"
minhook = { git = "https://github.com/Jascha-N/minhook-rs" }